#!/bin/bash
echo "Updating Vim environment..."
git pull --rebase --recurse-submodules origin master

# Ensure remotely added new submodules are considered.
git submodule update --recursive --init

# Ensure all plugins are on master and up to date.
git submodule foreach 'git checkout master && git pull origin master'

# Recompile YCM
# TODO: detect YCM change since last compilation
./bundle/youcompleteme/install.py --clang-completer --tern-completer

# Autocommit
git commit -am "Update bundle" && git push origin master

git status

echo " $COL_GREEN Update complete! $COL_RESET"
