#!/bin/bash
echo "Updating Vim environment..."
git pull --recurse-submodules origin master
git submodule update --recursive
echo "Updates fetched, checking status..."
git status
echo "Update completed! Please commit possible changes."
